version: "2"
services:
  vehicle-db:
    image: bitnami/postgresql:11.11.0-debian-10-r59
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: vehicle
      POSTGRES_USER: vehicle
      POSTGRES_PASSWORD: vehicle