apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vehicle-db
  labels:
    app.kubernetes.io/part-of: vehicle-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-db
  labels:
    app.kubernetes.io/part-of: vehicle-db
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: vehicle-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: vehicle-db
    spec:
      initContainers:
      - name: remove-lost-found
        image: busybox
        command:
        - sh
        - -c
        - |
          rm -fr /var/lib/postgresql/data/lost+found
        volumeMounts:
        - name: vehicle-db
          mountPath: /var/lib/postgresql/data
      containers:
      - image: bitnami/postgresql:11
        name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: vehicle-db
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: vehicle-db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vehicle-db
              key: password
        ports:
        - containerPort: 5432
          name: vehicle-db
        volumeMounts:
        - name: vehicle-db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: vehicle-db
        persistentVolumeClaim:
          claimName: vehicle-db
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-db
  labels:
    app.kubernetes.io/part-of: vehicle-db
spec:
  ports:
  - port: 5432
  selector:
    app.kubernetes.io/part-of: vehicle-db
---
apiVersion: v1
kind: Secret
metadata:
  name: vehicle-db
  labels:
    app.kubernetes.io/part-of: vehicle-db
type: servicebinding.io/postgresql
stringData:
  type: postgresql
  host: vehicle-db
  port: "5432"
  username: vehicle
  password: vehicle
  database: vehicle